interface Book {
  id: number
  title: string
  author: string
  category: string
  rating: number
  reviewCount: number
  coverUrl: string
  slug: string
  description: string
  price: number
  link: string
}
const allBooks: Book[] = [
  {
    id: 1,
    title: "Đắc Nhân Tâm",
    author: "Dale Carnegie",
    category: "Tự phát triển",
    rating: 4.8,
    reviewCount: 1250,
    coverUrl: "https://tiemsach.org/wp-content/uploads/2023/07/Ebook-Dac-nhan-tam.jpg",
    slug: "dac-nhan-tam",
    description: "Cuốn sách kinh điển về nghệ thuật giao tiếp và ứng xử",
    price: 120000,
    link: "https://thuviensachpdf.com/dac-nhan-tam"
  },
  {
    id: 2,
    title: "Tôi Thấy Hoa Vàng Trên Cỏ Xanh",
    author: "Nguyễn Nhật Ánh",
    category: "Văn học",
    rating: 4.7,
    reviewCount: 980,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/27/toi-thay-hoa-vang-tren-co-xanh.jpg",
    slug: "toi-thay-hoa-vang-tren-co-xanh",
    description: "Tiểu thuyết về tuổi thơ đầy cảm xúc",
    price: 85000,
    link: "https://thuviensachpdf.com/toi-thay-hoa-vang-tren-co-xanh"
  },
  {
    id: 3,
    title: "Từ Tốt Đến Vĩ Đại",
    author: "Jim Collins",
    category: "Kinh doanh",
    rating: 4.7,
    reviewCount: 1400,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/66/tu-tot-den-vi-dai.jpg",
    slug: "tu-tot-den-vi-dai",
    description: "Phân tích các yếu tố đưa doanh nghiệp từ tốt đến vĩ đại",
    price: 155000,
    link: "https://thuviensachpdf.com/tu-tot-den-vi-dai"
  },
  {
    id: 4,
    title: "Cha Giàu Cha Nghèo",
    author: "Robert Kiyosaki & Sharon Lechter",
    category: "Tài chính",
    rating: 4.6,
    reviewCount: 1750,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/76/cha-giau-cha-ngheo.jpg",
    slug: "cha-giau-cha-ngheo",
    description: "Bài học về tài chính cá nhân và tư duy đầu tư",
    price: 145000,
    link: "https://thuviensachpdf.com/cha-giau-cha-ngheo"
  },
  {
    id: 5,
    title: "Sức Mạnh Tiềm Thức",
    author: "Joseph Murphy",
    category: "Tự phát triển",
    rating: 4.6,
    reviewCount: 1300,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/99/suc-manh-tiem-thuc.jpg",
    slug: "suc-manh-tiem-thuc",
    description: "Khám phá sức mạnh của tiềm thức để đạt được thành công và hạnh phúc",
    price: 125000,
    link: "https://thuviensachpdf.com/suc-manh-tiem-thuc"
  },
  {
    id: 6,
    title: "Nhà Giả Kim",
    author: "Paulo Coelho",
    category: "Văn học",
    rating: 4.5,
    reviewCount: 1100,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/77/nha-gia-kim.jpg",
    slug: "nha-gia-kim",
    description: "Câu chuyện về hành trình tìm kiếm ước mơ",
    price: 110000,
    link: "https://thuviensachpdf.com/nha-gia-kim"
  },
  {
    id: 7,
    title: "Tư Duy Nhanh và Chậm",
    author: "Daniel Kahneman",
    category: "Tâm lý học",
    rating: 4.7,
    reviewCount: 1650,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/48/tu-duy-nhanh-va-cham.jpg",
    slug: "tu-duy-nhanh-va-cham",
    description: "Phân tích cách con người đưa ra quyết định",
    price: 160000,
    link: "https://thuviensachpdf.com/tu-duy-nhanh-va-cham"
  },
  {
    id: 8,
    title: "Cho Tôi Xin Một Vé Đi Tuổi Thơ",
    author: "Nguyễn Nhật Ánh",
    category: "Văn học",
    rating: 4.6,
    reviewCount: 870,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/10/cho-toi-xin-mot-ve-di-tuoi-tho.jpg",
    slug: "cho-toi-xin-mot-ve-di-tuoi-tho",
    description: "Hành trình trở về tuổi thơ đầy cảm xúc",
    price: 90000,
    link: "https://thuviensachpdf.com/cho-toi-xin-mot-ve-di-tuoi-tho"
  },
  {
    id: 9,
    title: "Bí Mật Tư Duy Triệu Phú",
    author: "T. Harv Eker",
    category: "Tự phát triển",
    rating: 4.5,
    reviewCount: 920,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/93/bi-mat-tu-duy-trieu-phu.jpg",
    slug: "bi-mat-tu-duy-trieu-phu",
    description: "Hướng dẫn tư duy để đạt được tự do tài chính",
    price: 130000,
    link: "https://thuviensachpdf.com/bi-mat-tu-duy-trieu-phu"
  },
  {
    id: 10,
    title: "1984",
    author: "George Orwell",
    category: "Văn học",
    rating: 4.8,
    reviewCount: 2000,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/51/1984.jpg",
    slug: "1984",
    description: "Tiểu thuyết dystopia kinh điển về xã hội toàn trị",
    price: 140000,
    link: "https://thuviensachpdf.com/1984"
  },
  {
    id: 11,
    title: "Hoàng Tử Bé",
    author: "Antoine de Saint-Exupéry",
    category: "Văn học",
    rating: 4.7,
    reviewCount: 1300,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/12/hoang-tu-be.jpg",
    slug: "hoang-tu-be",
    description: "Câu chuyện ý nghĩa về tình bạn và ý nghĩa cuộc sống",
    price: 100000,
    link: "https://thuviensachpdf.com/hoang-tu-be"
  },
  {
    id: 12,
    title: "Dám Bị Ghét",
    author: "Ichiro Kishimi & Fumitake Koga",
    category: "Tự phát triển",
    rating: 4.6,
    reviewCount: 1050,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/14/dam-bi-ghet.jpg",
    slug: "dam-bi-ghet",
    description: "Triết lý Adler về sự tự do và hạnh phúc",
    price: 115000,
    link: "https://thuviensachpdf.com/dam-bi-ghet"
  },
  {
    id: 13,
    title: "Cà Phê Cùng Tony",
    author: "Tony Buổi Sáng",
    category: "Tự phát triển",
    rating: 4.4,
    reviewCount: 890,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/68/ca-phe-cung-tony.jpg",
    slug: "ca-phe-cung-tony",
    description: "Những câu chuyện truyền cảm hứng cho giới trẻ",
    price: 95000,
    link: "https://thuviensachpdf.com/ca-phe-cung-tony"
  },
  {
    id: 14,
    title: "Tội Ác và Hình Phạt",
    author: "Fyodor Dostoevsky",
    category: "Văn học",
    rating: 4.7,
    reviewCount: 1400,
    coverUrl: "https://www.gutenberg.org/cache/epub/2554/pg2554.cover.medium.jpg",
    slug: "toi-ac-va-hinh-phat",
    description: "Tiểu thuyết tâm lý về tội lỗi và chuộc tội",
    price: 135000,
    link: "https://www.gutenberg.org/ebooks/2554"
  },
  {
    id: 15,
    title: "Người Giàu Có Nhất Thành Babylon",
    author: "George S. Clason",
    category: "Tài chính",
    rating: 4.6,
    reviewCount: 1000,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/71/nguoi-giau-co-nhat-thanh-babylon.jpg",
    slug: "nguoi-giau-co-nhat-thanh-babylon",
    description: "Bài học tài chính qua những câu chuyện cổ",
    price: 110000,
    link: "https://thuviensachpdf.com/nguoi-giau-co-nhat-thanh-babylon"
  },
  {
    id: 16,
    title: "Đồi Gió Hú",
    author: "Emily Brontë",
    category: "Văn học",
    rating: 4.5,
    reviewCount: 1200,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/44/doi-gio-hu.jpg",
    slug: "doi-gio-hu",
    description: "Tiểu thuyết lãng mạn kinh điển về tình yêu và thù hận",
    price: 125000,
    link: "https://thuviensachpdf.com/doi-gio-hu"
  },
  {
    id: 17,
    title: "Homo Deus: Lược Sử Tương Lai",
    author: "Yuval Noah Harari",
    category: "Lịch sử",
    rating: 4.8,
    reviewCount: 1700,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/37/homo-deus-luoc-su-tuong-lai.jpg",
    slug: "homo-deus",
    description: "Tương lai của loài người trong kỷ nguyên công nghệ",
    price: 190000,
    link: "https://thuviensachpdf.com/homo-deus-luoc-su-tuong-lai"
  },
  {
    id: 18,
    title: "Mắt Biếc",
    author: "Nguyễn Nhật Ánh",
    category: "Văn học",
    rating: 4.6,
    reviewCount: 950,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/63/mat-biec.jpg",
    slug: "mat-biec",
    description: "Câu chuyện tình yêu đầy day dứt của tuổi trẻ",
    price: 90000,
    link: "https://thuviensachpdf.com/mat-biec"
  },
  {
    id: 19,
    title: "Bố Già",
    author: "Mario Puzo",
    category: "Văn học",
    rating: 4.8,
    reviewCount: 1600,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/99/bo-gia.jpg",
    slug: "bo-gia",
    description: "Tiểu thuyết về thế giới mafia đầy kịch tính",
    price: 140000,
    link: "https://thuviensachpdf.com/bo-gia"
  },
  {
    id: 20,
    title: "7 Thói Để Thành Đạt",
    author: "Stephen R. Covey",
    category: "Tự phát triển",
    rating: 4.7,
    reviewCount: 1350,
    coverUrl: "https://nhasachmienphi.com/wp-content/uploads/7-thoi-quen-de-thanh-dat.jpg",
    slug: "7-thoi-quen-hieu-qua",
    description: "Hướng dẫn xây dựng thói quen để thành công",
    price: 145000,
    link: "https://nlv.edu.vn/wp-content/uploads/2021/08/7thoi_quen_de_thanh_dat.pdf"
  },
  {
    id: 21,
    title: "Chí Phèo",
    author: "Nam Cao",
    category: "Văn học",
    rating: 4.5,
    reviewCount: 800,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/50/chi-pheo.jpg",
    slug: "chi-pheo",
    description: "Tác phẩm hiện thực phê phán về số phận con người",
    price: 75000,
    link: "https://thuviensachpdf.com/chi-pheo"
  },
  {
    id: 22,
    title: "Tâm Lý Học Thành Công",
    author: "Carol S. Dweck",
    category: "Tâm lý học",
    rating: 4.6,
    reviewCount: 1100,
    coverUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCrS1ZpkeR_mBrvZ0UnlZBU3nq-BGxV0AuBA&s",
    slug: "tam-ly-hoc-thanh-cong",
    description: "Khám phá tư duy phát triển để đạt thành công",
    price: 130000,
    link: "https://dilib.vn/pdf/viewer.php?id=1ce214"
  },
  {
    id: 23,
    title: "Những Người Khốn Khổ",
    author: "Victor Hugo",
    category: "Văn học",
    rating: 4.8,
    reviewCount: 1500,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/48/nhung-nguoi-khon-kho.jpg",
    slug: "nhung-nguoi-khon-kho",
    description: "Tác phẩm kinh điển về lòng nhân ái và công lý",
    price: 160000,
    link: "https://thuviensachpdf.com/nhung-nguoi-khon-kho#google_vignette"
  },
  {
    id: 24,
    title: "Hài Hước Một Chút Thế Giới Sẽ Khác Đi",
    author: "The Book Worm",
    category: "Tự phát triển",
    rating: 4.3,
    reviewCount: 700,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/78/hai-huoc-mot-chut-the-gioi-se-khac-di.jpg",
    slug: "hai-huoc-mot-chut",
    description: "Sử dụng hài hước để thay đổi cuộc sống",
    price: 95000,
    link: "https://thuviensachpdf.com/hai-huoc-mot-chut-the-gioi-se-khac-di"
  },
  {
    id: 25,
    title: "Hành Trình Về Phương Đông",
    author: "Baird T. Spalding",
    category: "Tâm linh",
    rating: 4.5,
    reviewCount: 850,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/98/hanh-trinh-ve-phuong-dong.jpg",
    slug: "hanh-trinh-ve-phuong-dong",
    description: "Khám phá tâm linh và triết lý phương Đông",
    price: 110000,
    link: "https://thuviensachpdf.com/hanh-trinh-ve-phuong-dong"
  },
  {
    id: 26,
    title: "Tắt Đèn",
    author: "Ngô Tất Tố",
    category: "Văn học",
    rating: 4.4,
    reviewCount: 650,
    coverUrl: "https://nhasachmienphi.com/images/thumbnail/nhasachmienphi-tat-den.jpg",
    slug: "tat-den",
    description: "Tác phẩm hiện thực về số phận người nông dân",
    price: 80000,
    link: "https://file.nhasachmienphi.com/pdf/nhasachmienphi-tat-den.pdf"
  },
  {
    id: 27,
    title: "Đi Tìm Lẽ Sống",
    author: "Viktor E. Frankl",
    category: "Tâm lý học",
    rating: 4.7,
    reviewCount: 1200,
    coverUrl: "https://thuviensachpdf.com/uploads/book/image/99/di-tim-le-song.jpg",
    slug: "di-tim-le-song",
    description: "Hành trình tìm ý nghĩa cuộc sống qua nghịch cảnh",
    price: 125000,
    link: "https://thuviensachpdf.com/di-tim-le-song"
  },
  {
    id: 28,
    title: "Bí Mật",
    author: "Rhonda Byrne",
    category: "Tự phát triển",
    rating: 4.4,
    reviewCount: 1000,
    coverUrl: "https://pos.nvncdn.com/fd5775-40602/ps/20240504_ZVvi7lLZ0b.jpeg",
    slug: "bi-mat",
    description: "Khám phá quy luật thu hút để thành công",
    price: 115000,
    link: "https://khoahoctamlinh.vn/pdf/viewer.php?id=5735"
  }
];
export default allBooks;